### ISSUE TITLE
Incompatibility with Limitless

### ISSUE THREAD

**Issue by ConqAra** [Latokike/lato-origins#1]
Crashes when you have the Limitless mod.

Mod: [Limitless](https://github.com/user11681/limitless)
Log: [https://pastebin.com/qBamhtsM](https://pastebin.com/qBamhtsM)

**Comment by latokike** [comment]
I don't think it was lato origins and limitless, as i ran them together and they didn't crash.

**Comment by enigmaticectasy** [comment]
No idea what's causing it for me, but i can't even seem to run it with even the bare minimum requirements for mods, so i'm going to take a guess that it's an outdated dependency that you're using.

**Comment by enigmaticectasy** [comment]
I think it's an issue with the mod itself, not incompatibilities, i tried with bare minimum and it doesn't seem to work, double checked a few times and nothing seems to work.

EDIT: Latoorigins0.4.0 works with the bare minimum reqs (Fabricapi, origins, pehkui) on 1.16.4, Aswell as Latoorigins0.5.0, but 0.5.1 and up has issues and won't load, including the newest version with 1.16.5 OR 1.16.4. I'm guessing it's linked to latoorigins.mixins.json, but i can't say for certain since i don't really know code, so it's just a guess with what error is spewed at me, which is pretty similar to Conq's.

**Comment by latokike** [comment]
The game doesn't crash on start up anymore with the latest update
