### ISSUE TITLE
Compatibility issues

### ISSUE THREAD

**Issue by JoJazzy** [Latokike/lato-origins#6]
I'm currently attempting to make a modpack that includes your mod (which is quite honestly really fun and well made, good job) and it seems to have compatibility issues with some of the mods I have installed, noteably Jumploader (which is a mod that allows for Fabric modpacks to be made on the CurseForge launcher) and quite possibly it conflicts with some of the Origins addons I have installed though I'm not so sure about that. 
When I attempt to load up the game it crashes before even showing the loading screen, the launcher gives back Error number: 0
Here's a log of me trying to boot it up (It seems to be a critical injection failure,  something to do with getAttributeModifiers):
[2021-04-18-1.log](https://github.com/Latokike/lato-origins/files/6332100/2021-04-18-1.log)

(If this is something unrelated to your mod or something you can't/won't fix, I'm sory for wasting your time and thank you for listening anyways)

**Comment by Originbrine** [comment]
i have the same issue with jumploader if you use the bare minimum jumploader makes it crash plus can you send me a copy if the mod pack please?

**Comment by CammiePone** [comment]
The crash you're having, JoJazzy, is because the author of Lato Origins used some of Extra Origins' code. In the process, they violated the license of Extra Origins.

The code in question happens to be a Redirect, and Redirects have a small problem of not being compatible with one another if they're targeting the same thing. The only solution would be if Lato Origins depended on Extra Origins, which would solve the crash and the licensing issues.

Otherwise, Lato Origins has to change the license on both Github and CurseForge to GNU GPL v3.0 to comply with Extra Origins' license. However, that won't solve the crash between the two mods, and as a result you, the player, would be forced to use one or the other. Moriya, the author of Extra Origins, has already tried to get in contact with Latokike, but I'm not sure if he has gotten any response so far.

**Comment by MoriyaShiine** [comment]
I still don't have a response but I'm skeptical that it's malicious intent.

**Comment by JoJazzy** [comment]
> The crash you're having, JoJazzy, is because the author of Lato Origins used some of Extra Origins' code. In the process, they violated the license of Extra Origins.
> 
> The code in question happens to be a Redirect, and Redirects have a small problem of not being compatible with one another if they're targeting the same thing. The only solution would be if Lato Origins depended on Extra Origins, which would solve the crash and the licensing issues.
> 
> Otherwise, Lato Origins has to change the license on both Github and CurseForge to GNU GPL v3.0 to comply with Extra Origins' license. However, that won't solve the crash between the two mods, and as a result you, the player, would be forced to use one or the other. Moriya, the author of Extra Origins, has already tried to get in contact with Latokike, but I'm not sure if he has gotten any response so far.

Damn, that sucks.
I'm not in a particular hurry or really in need of it being included so it's fine, but I hope that will be fixed it the future, I'll include Lato Origins in my modpack then

**Comment by MoriyaShiine** [comment]
This can be closed now

**Comment by latokike** [comment]
The latest update has fixed the compatibility issues.

**Comment by JoJazzy** [comment]
Thank you so much!
It's greatly appreciated
